version : "3.7"

networks:
  prudence:

services:
  portainer:
    image: portainer/portainer
    ports:
      - "3005:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  node-app:
    image : parvezyellow/prudence
    ports:
      - "3000:3000"
    networks:
      - prudence

  nginx:
    image: parvezyellow/prudence-nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - prudence
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt/
  jenkins:
    image: parvezyellow/jenkins
    user: root
    ports:
      - "3006:8080"
      - "3007:50000"
    volumes:
      - ~/jenkins:/var/jenkins_home #Remember that, the tmp directory is designed to be wiped on system reboot.
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  portainer_data:

